package cn.org.hbca.project.model;

public class Dialogitemconfig {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dialogitemconfig.pId
     *
     * @mbggenerated Tue Nov 04 22:34:35 CST 2014
     */
    private String pId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dialogitemconfig.itemType
     *
     * @mbggenerated Tue Nov 04 22:34:35 CST 2014
     */
    private String itemType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dialogitemconfig.itemClick
     *
     * @mbggenerated Tue Nov 04 22:34:35 CST 2014
     */
    private String itemClick;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dialogitemconfig.itemName
     *
     * @mbggenerated Tue Nov 04 22:34:35 CST 2014
     */
    private String itemName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dialogitemconfig.itemValue
     *
     * @mbggenerated Tue Nov 04 22:34:35 CST 2014
     */
    private String itemValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dialogitemconfig.pId
     *
     * @return the value of dialogitemconfig.pId
     *
     * @mbggenerated Tue Nov 04 22:34:35 CST 2014
     */
    public String getpId() {
        return pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dialogitemconfig.pId
     *
     * @param pId the value for dialogitemconfig.pId
     *
     * @mbggenerated Tue Nov 04 22:34:35 CST 2014
     */
    public void setpId(String pId) {
        this.pId = pId == null ? null : pId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dialogitemconfig.itemType
     *
     * @return the value of dialogitemconfig.itemType
     *
     * @mbggenerated Tue Nov 04 22:34:35 CST 2014
     */
    public String getItemType() {
        return itemType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dialogitemconfig.itemType
     *
     * @param itemType the value for dialogitemconfig.itemType
     *
     * @mbggenerated Tue Nov 04 22:34:35 CST 2014
     */
    public void setItemType(String itemType) {
        this.itemType = itemType == null ? null : itemType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dialogitemconfig.itemClick
     *
     * @return the value of dialogitemconfig.itemClick
     *
     * @mbggenerated Tue Nov 04 22:34:35 CST 2014
     */
    public String getItemClick() {
        return itemClick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dialogitemconfig.itemClick
     *
     * @param itemClick the value for dialogitemconfig.itemClick
     *
     * @mbggenerated Tue Nov 04 22:34:35 CST 2014
     */
    public void setItemClick(String itemClick) {
        this.itemClick = itemClick == null ? null : itemClick.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dialogitemconfig.itemName
     *
     * @return the value of dialogitemconfig.itemName
     *
     * @mbggenerated Tue Nov 04 22:34:35 CST 2014
     */
    public String getItemName() {
        return itemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dialogitemconfig.itemName
     *
     * @param itemName the value for dialogitemconfig.itemName
     *
     * @mbggenerated Tue Nov 04 22:34:35 CST 2014
     */
    public void setItemName(String itemName) {
        this.itemName = itemName == null ? null : itemName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dialogitemconfig.itemValue
     *
     * @return the value of dialogitemconfig.itemValue
     *
     * @mbggenerated Tue Nov 04 22:34:35 CST 2014
     */
    public String getItemValue() {
        return itemValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dialogitemconfig.itemValue
     *
     * @param itemValue the value for dialogitemconfig.itemValue
     *
     * @mbggenerated Tue Nov 04 22:34:35 CST 2014
     */
    public void setItemValue(String itemValue) {
        this.itemValue = itemValue == null ? null : itemValue.trim();
    }
}