package cn.org.hbca.project.model;

import java.util.Date;

public class Projectinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projectinfo.ProjectId
     *
     * @mbggenerated Sun Sep 28 21:58:29 CST 2014
     */
    private String projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projectinfo.ProjectName
     *
     * @mbggenerated Sun Sep 28 21:58:29 CST 2014
     */
    private String projectName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projectinfo.ProjectManager
     *
     * @mbggenerated Sun Sep 28 21:58:29 CST 2014
     */
    private String projectManager;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projectinfo.ManufacturerName
     *
     * @mbggenerated Sun Sep 28 21:58:29 CST 2014
     */
    private String manufacturerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projectinfo.ManufacturerProjectName
     *
     * @mbggenerated Sun Sep 28 21:58:29 CST 2014
     */
    private String manufacturerProjectName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projectinfo.ManufacturerProjectManager
     *
     * @mbggenerated Sun Sep 28 21:58:29 CST 2014
     */
    private String manufacturerProjectManager;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projectinfo.ManufacturerProjectDeveloper
     *
     * @mbggenerated Sun Sep 28 21:58:29 CST 2014
     */
    private String manufacturerProjectDeveloper;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projectinfo.MPMContact
     *
     * @mbggenerated Sun Sep 28 21:58:29 CST 2014
     */
    private String MPMContact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projectinfo.MPDContact
     *
     * @mbggenerated Sun Sep 28 21:58:29 CST 2014
     */
    private String MPDContact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projectinfo.PlanDevStartDate
     *
     * @mbggenerated Sun Sep 28 21:58:29 CST 2014
     */
    private Date planDevStartDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projectinfo.ActualDevStartDate
     *
     * @mbggenerated Sun Sep 28 21:58:29 CST 2014
     */
    private Date actualDevStartDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projectinfo.PlanAcceptDate
     *
     * @mbggenerated Sun Sep 28 21:58:29 CST 2014
     */
    private Date planAcceptDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projectinfo.ActualAcceptDate
     *
     * @mbggenerated Sun Sep 28 21:58:29 CST 2014
     */
    private Date actualAcceptDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projectinfo.DevTech
     *
     * @mbggenerated Sun Sep 28 21:58:29 CST 2014
     */
    private String devTech;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projectinfo.NetWorkEnvironment
     *
     * @mbggenerated Sun Sep 28 21:58:29 CST 2014
     */
    private String netWorkEnvironment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projectinfo.ServerEnvironment
     *
     * @mbggenerated Sun Sep 28 21:58:29 CST 2014
     */
    private String serverEnvironment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projectinfo.ClientEnvironment
     *
     * @mbggenerated Sun Sep 28 21:58:29 CST 2014
     */
    private String clientEnvironment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projectinfo.OtherEnvironment
     *
     * @mbggenerated Sun Sep 28 21:58:29 CST 2014
     */
    private String otherEnvironment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projectinfo.FunctionsNeededIntegrate
     *
     * @mbggenerated Sun Sep 28 21:58:29 CST 2014
     */
    private String functionsNeededIntegrate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projectinfo.ProjectCode
     *
     * @mbggenerated Sun Sep 28 21:58:29 CST 2014
     */
    private String projectCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projectinfo.IncreaseIssue
     *
     * @mbggenerated Sun Sep 28 21:58:29 CST 2014
     */
    private String increaseIssue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projectinfo.EncryptFileLimit
     *
     * @mbggenerated Sun Sep 28 21:58:29 CST 2014
     */
    private String encryptFileLimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projectinfo.KeepEncryptKey
     *
     * @mbggenerated Sun Sep 28 21:58:29 CST 2014
     */
    private Boolean keepEncryptKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projectinfo.MultiOperation
     *
     * @mbggenerated Sun Sep 28 21:58:29 CST 2014
     */
    private String multiOperation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projectinfo.KeyManufacture
     *
     * @mbggenerated Sun Sep 28 21:58:29 CST 2014
     */
    private String keyManufacture;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projectinfo.SVSServerType
     *
     * @mbggenerated Sun Sep 28 21:58:29 CST 2014
     */
    private String SVSServerType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projectinfo.TSSServerType
     *
     * @mbggenerated Sun Sep 28 21:58:29 CST 2014
     */
    private String TSSServerType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projectinfo.SealType
     *
     * @mbggenerated Sun Sep 28 21:58:29 CST 2014
     */
    private String sealType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projectinfo.ProjectInitDate
     *
     * @mbggenerated Sun Sep 28 21:58:29 CST 2014
     */
    private Date projectInitDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projectinfo.ProjectStatus
     *
     * @mbggenerated Sun Sep 28 21:58:29 CST 2014
     */
    private String projectStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projectinfo.ProjectId
     *
     * @return the value of projectinfo.ProjectId
     *
     * @mbggenerated Sun Sep 28 21:58:29 CST 2014
     */
    public String getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projectinfo.ProjectId
     *
     * @param projectId the value for projectinfo.ProjectId
     *
     * @mbggenerated Sun Sep 28 21:58:29 CST 2014
     */
    public void setProjectId(String projectId) {
        this.projectId = projectId == null ? null : projectId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projectinfo.ProjectName
     *
     * @return the value of projectinfo.ProjectName
     *
     * @mbggenerated Sun Sep 28 21:58:29 CST 2014
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projectinfo.ProjectName
     *
     * @param projectName the value for projectinfo.ProjectName
     *
     * @mbggenerated Sun Sep 28 21:58:29 CST 2014
     */
    public void setProjectName(String projectName) {
        this.projectName = projectName == null ? null : projectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projectinfo.ProjectManager
     *
     * @return the value of projectinfo.ProjectManager
     *
     * @mbggenerated Sun Sep 28 21:58:29 CST 2014
     */
    public String getProjectManager() {
        return projectManager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projectinfo.ProjectManager
     *
     * @param projectManager the value for projectinfo.ProjectManager
     *
     * @mbggenerated Sun Sep 28 21:58:29 CST 2014
     */
    public void setProjectManager(String projectManager) {
        this.projectManager = projectManager == null ? null : projectManager.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projectinfo.ManufacturerName
     *
     * @return the value of projectinfo.ManufacturerName
     *
     * @mbggenerated Sun Sep 28 21:58:29 CST 2014
     */
    public String getManufacturerName() {
        return manufacturerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projectinfo.ManufacturerName
     *
     * @param manufacturerName the value for projectinfo.ManufacturerName
     *
     * @mbggenerated Sun Sep 28 21:58:29 CST 2014
     */
    public void setManufacturerName(String manufacturerName) {
        this.manufacturerName = manufacturerName == null ? null : manufacturerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projectinfo.ManufacturerProjectName
     *
     * @return the value of projectinfo.ManufacturerProjectName
     *
     * @mbggenerated Sun Sep 28 21:58:29 CST 2014
     */
    public String getManufacturerProjectName() {
        return manufacturerProjectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projectinfo.ManufacturerProjectName
     *
     * @param manufacturerProjectName the value for projectinfo.ManufacturerProjectName
     *
     * @mbggenerated Sun Sep 28 21:58:29 CST 2014
     */
    public void setManufacturerProjectName(String manufacturerProjectName) {
        this.manufacturerProjectName = manufacturerProjectName == null ? null : manufacturerProjectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projectinfo.ManufacturerProjectManager
     *
     * @return the value of projectinfo.ManufacturerProjectManager
     *
     * @mbggenerated Sun Sep 28 21:58:29 CST 2014
     */
    public String getManufacturerProjectManager() {
        return manufacturerProjectManager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projectinfo.ManufacturerProjectManager
     *
     * @param manufacturerProjectManager the value for projectinfo.ManufacturerProjectManager
     *
     * @mbggenerated Sun Sep 28 21:58:29 CST 2014
     */
    public void setManufacturerProjectManager(String manufacturerProjectManager) {
        this.manufacturerProjectManager = manufacturerProjectManager == null ? null : manufacturerProjectManager.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projectinfo.ManufacturerProjectDeveloper
     *
     * @return the value of projectinfo.ManufacturerProjectDeveloper
     *
     * @mbggenerated Sun Sep 28 21:58:29 CST 2014
     */
    public String getManufacturerProjectDeveloper() {
        return manufacturerProjectDeveloper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projectinfo.ManufacturerProjectDeveloper
     *
     * @param manufacturerProjectDeveloper the value for projectinfo.ManufacturerProjectDeveloper
     *
     * @mbggenerated Sun Sep 28 21:58:29 CST 2014
     */
    public void setManufacturerProjectDeveloper(String manufacturerProjectDeveloper) {
        this.manufacturerProjectDeveloper = manufacturerProjectDeveloper == null ? null : manufacturerProjectDeveloper.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projectinfo.MPMContact
     *
     * @return the value of projectinfo.MPMContact
     *
     * @mbggenerated Sun Sep 28 21:58:29 CST 2014
     */
    public String getMPMContact() {
        return MPMContact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projectinfo.MPMContact
     *
     * @param MPMContact the value for projectinfo.MPMContact
     *
     * @mbggenerated Sun Sep 28 21:58:29 CST 2014
     */
    public void setMPMContact(String MPMContact) {
        this.MPMContact = MPMContact == null ? null : MPMContact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projectinfo.MPDContact
     *
     * @return the value of projectinfo.MPDContact
     *
     * @mbggenerated Sun Sep 28 21:58:29 CST 2014
     */
    public String getMPDContact() {
        return MPDContact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projectinfo.MPDContact
     *
     * @param MPDContact the value for projectinfo.MPDContact
     *
     * @mbggenerated Sun Sep 28 21:58:29 CST 2014
     */
    public void setMPDContact(String MPDContact) {
        this.MPDContact = MPDContact == null ? null : MPDContact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projectinfo.PlanDevStartDate
     *
     * @return the value of projectinfo.PlanDevStartDate
     *
     * @mbggenerated Sun Sep 28 21:58:29 CST 2014
     */
    public Date getPlanDevStartDate() {
        return planDevStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projectinfo.PlanDevStartDate
     *
     * @param planDevStartDate the value for projectinfo.PlanDevStartDate
     *
     * @mbggenerated Sun Sep 28 21:58:29 CST 2014
     */
    public void setPlanDevStartDate(Date planDevStartDate) {
        this.planDevStartDate = planDevStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projectinfo.ActualDevStartDate
     *
     * @return the value of projectinfo.ActualDevStartDate
     *
     * @mbggenerated Sun Sep 28 21:58:29 CST 2014
     */
    public Date getActualDevStartDate() {
        return actualDevStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projectinfo.ActualDevStartDate
     *
     * @param actualDevStartDate the value for projectinfo.ActualDevStartDate
     *
     * @mbggenerated Sun Sep 28 21:58:29 CST 2014
     */
    public void setActualDevStartDate(Date actualDevStartDate) {
        this.actualDevStartDate = actualDevStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projectinfo.PlanAcceptDate
     *
     * @return the value of projectinfo.PlanAcceptDate
     *
     * @mbggenerated Sun Sep 28 21:58:29 CST 2014
     */
    public Date getPlanAcceptDate() {
        return planAcceptDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projectinfo.PlanAcceptDate
     *
     * @param planAcceptDate the value for projectinfo.PlanAcceptDate
     *
     * @mbggenerated Sun Sep 28 21:58:29 CST 2014
     */
    public void setPlanAcceptDate(Date planAcceptDate) {
        this.planAcceptDate = planAcceptDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projectinfo.ActualAcceptDate
     *
     * @return the value of projectinfo.ActualAcceptDate
     *
     * @mbggenerated Sun Sep 28 21:58:29 CST 2014
     */
    public Date getActualAcceptDate() {
        return actualAcceptDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projectinfo.ActualAcceptDate
     *
     * @param actualAcceptDate the value for projectinfo.ActualAcceptDate
     *
     * @mbggenerated Sun Sep 28 21:58:29 CST 2014
     */
    public void setActualAcceptDate(Date actualAcceptDate) {
        this.actualAcceptDate = actualAcceptDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projectinfo.DevTech
     *
     * @return the value of projectinfo.DevTech
     *
     * @mbggenerated Sun Sep 28 21:58:29 CST 2014
     */
    public String getDevTech() {
        return devTech;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projectinfo.DevTech
     *
     * @param devTech the value for projectinfo.DevTech
     *
     * @mbggenerated Sun Sep 28 21:58:29 CST 2014
     */
    public void setDevTech(String devTech) {
        this.devTech = devTech == null ? null : devTech.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projectinfo.NetWorkEnvironment
     *
     * @return the value of projectinfo.NetWorkEnvironment
     *
     * @mbggenerated Sun Sep 28 21:58:29 CST 2014
     */
    public String getNetWorkEnvironment() {
        return netWorkEnvironment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projectinfo.NetWorkEnvironment
     *
     * @param netWorkEnvironment the value for projectinfo.NetWorkEnvironment
     *
     * @mbggenerated Sun Sep 28 21:58:29 CST 2014
     */
    public void setNetWorkEnvironment(String netWorkEnvironment) {
        this.netWorkEnvironment = netWorkEnvironment == null ? null : netWorkEnvironment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projectinfo.ServerEnvironment
     *
     * @return the value of projectinfo.ServerEnvironment
     *
     * @mbggenerated Sun Sep 28 21:58:29 CST 2014
     */
    public String getServerEnvironment() {
        return serverEnvironment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projectinfo.ServerEnvironment
     *
     * @param serverEnvironment the value for projectinfo.ServerEnvironment
     *
     * @mbggenerated Sun Sep 28 21:58:29 CST 2014
     */
    public void setServerEnvironment(String serverEnvironment) {
        this.serverEnvironment = serverEnvironment == null ? null : serverEnvironment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projectinfo.ClientEnvironment
     *
     * @return the value of projectinfo.ClientEnvironment
     *
     * @mbggenerated Sun Sep 28 21:58:29 CST 2014
     */
    public String getClientEnvironment() {
        return clientEnvironment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projectinfo.ClientEnvironment
     *
     * @param clientEnvironment the value for projectinfo.ClientEnvironment
     *
     * @mbggenerated Sun Sep 28 21:58:29 CST 2014
     */
    public void setClientEnvironment(String clientEnvironment) {
        this.clientEnvironment = clientEnvironment == null ? null : clientEnvironment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projectinfo.OtherEnvironment
     *
     * @return the value of projectinfo.OtherEnvironment
     *
     * @mbggenerated Sun Sep 28 21:58:29 CST 2014
     */
    public String getOtherEnvironment() {
        return otherEnvironment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projectinfo.OtherEnvironment
     *
     * @param otherEnvironment the value for projectinfo.OtherEnvironment
     *
     * @mbggenerated Sun Sep 28 21:58:29 CST 2014
     */
    public void setOtherEnvironment(String otherEnvironment) {
        this.otherEnvironment = otherEnvironment == null ? null : otherEnvironment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projectinfo.FunctionsNeededIntegrate
     *
     * @return the value of projectinfo.FunctionsNeededIntegrate
     *
     * @mbggenerated Sun Sep 28 21:58:29 CST 2014
     */
    public String getFunctionsNeededIntegrate() {
        return functionsNeededIntegrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projectinfo.FunctionsNeededIntegrate
     *
     * @param functionsNeededIntegrate the value for projectinfo.FunctionsNeededIntegrate
     *
     * @mbggenerated Sun Sep 28 21:58:29 CST 2014
     */
    public void setFunctionsNeededIntegrate(String functionsNeededIntegrate) {
        this.functionsNeededIntegrate = functionsNeededIntegrate == null ? null : functionsNeededIntegrate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projectinfo.ProjectCode
     *
     * @return the value of projectinfo.ProjectCode
     *
     * @mbggenerated Sun Sep 28 21:58:29 CST 2014
     */
    public String getProjectCode() {
        return projectCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projectinfo.ProjectCode
     *
     * @param projectCode the value for projectinfo.ProjectCode
     *
     * @mbggenerated Sun Sep 28 21:58:29 CST 2014
     */
    public void setProjectCode(String projectCode) {
        this.projectCode = projectCode == null ? null : projectCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projectinfo.IncreaseIssue
     *
     * @return the value of projectinfo.IncreaseIssue
     *
     * @mbggenerated Sun Sep 28 21:58:29 CST 2014
     */
    public String getIncreaseIssue() {
        return increaseIssue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projectinfo.IncreaseIssue
     *
     * @param increaseIssue the value for projectinfo.IncreaseIssue
     *
     * @mbggenerated Sun Sep 28 21:58:29 CST 2014
     */
    public void setIncreaseIssue(String increaseIssue) {
        this.increaseIssue = increaseIssue == null ? null : increaseIssue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projectinfo.EncryptFileLimit
     *
     * @return the value of projectinfo.EncryptFileLimit
     *
     * @mbggenerated Sun Sep 28 21:58:29 CST 2014
     */
    public String getEncryptFileLimit() {
        return encryptFileLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projectinfo.EncryptFileLimit
     *
     * @param encryptFileLimit the value for projectinfo.EncryptFileLimit
     *
     * @mbggenerated Sun Sep 28 21:58:29 CST 2014
     */
    public void setEncryptFileLimit(String encryptFileLimit) {
        this.encryptFileLimit = encryptFileLimit == null ? null : encryptFileLimit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projectinfo.KeepEncryptKey
     *
     * @return the value of projectinfo.KeepEncryptKey
     *
     * @mbggenerated Sun Sep 28 21:58:29 CST 2014
     */
    public Boolean getKeepEncryptKey() {
        return keepEncryptKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projectinfo.KeepEncryptKey
     *
     * @param keepEncryptKey the value for projectinfo.KeepEncryptKey
     *
     * @mbggenerated Sun Sep 28 21:58:29 CST 2014
     */
    public void setKeepEncryptKey(Boolean keepEncryptKey) {
        this.keepEncryptKey = keepEncryptKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projectinfo.MultiOperation
     *
     * @return the value of projectinfo.MultiOperation
     *
     * @mbggenerated Sun Sep 28 21:58:29 CST 2014
     */
    public String getMultiOperation() {
        return multiOperation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projectinfo.MultiOperation
     *
     * @param multiOperation the value for projectinfo.MultiOperation
     *
     * @mbggenerated Sun Sep 28 21:58:29 CST 2014
     */
    public void setMultiOperation(String multiOperation) {
        this.multiOperation = multiOperation == null ? null : multiOperation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projectinfo.KeyManufacture
     *
     * @return the value of projectinfo.KeyManufacture
     *
     * @mbggenerated Sun Sep 28 21:58:29 CST 2014
     */
    public String getKeyManufacture() {
        return keyManufacture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projectinfo.KeyManufacture
     *
     * @param keyManufacture the value for projectinfo.KeyManufacture
     *
     * @mbggenerated Sun Sep 28 21:58:29 CST 2014
     */
    public void setKeyManufacture(String keyManufacture) {
        this.keyManufacture = keyManufacture == null ? null : keyManufacture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projectinfo.SVSServerType
     *
     * @return the value of projectinfo.SVSServerType
     *
     * @mbggenerated Sun Sep 28 21:58:29 CST 2014
     */
    public String getSVSServerType() {
        return SVSServerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projectinfo.SVSServerType
     *
     * @param SVSServerType the value for projectinfo.SVSServerType
     *
     * @mbggenerated Sun Sep 28 21:58:29 CST 2014
     */
    public void setSVSServerType(String SVSServerType) {
        this.SVSServerType = SVSServerType == null ? null : SVSServerType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projectinfo.TSSServerType
     *
     * @return the value of projectinfo.TSSServerType
     *
     * @mbggenerated Sun Sep 28 21:58:29 CST 2014
     */
    public String getTSSServerType() {
        return TSSServerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projectinfo.TSSServerType
     *
     * @param TSSServerType the value for projectinfo.TSSServerType
     *
     * @mbggenerated Sun Sep 28 21:58:29 CST 2014
     */
    public void setTSSServerType(String TSSServerType) {
        this.TSSServerType = TSSServerType == null ? null : TSSServerType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projectinfo.SealType
     *
     * @return the value of projectinfo.SealType
     *
     * @mbggenerated Sun Sep 28 21:58:29 CST 2014
     */
    public String getSealType() {
        return sealType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projectinfo.SealType
     *
     * @param sealType the value for projectinfo.SealType
     *
     * @mbggenerated Sun Sep 28 21:58:29 CST 2014
     */
    public void setSealType(String sealType) {
        this.sealType = sealType == null ? null : sealType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projectinfo.ProjectInitDate
     *
     * @return the value of projectinfo.ProjectInitDate
     *
     * @mbggenerated Sun Sep 28 21:58:29 CST 2014
     */
    public Date getProjectInitDate() {
        return projectInitDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projectinfo.ProjectInitDate
     *
     * @param projectInitDate the value for projectinfo.ProjectInitDate
     *
     * @mbggenerated Sun Sep 28 21:58:29 CST 2014
     */
    public void setProjectInitDate(Date projectInitDate) {
        this.projectInitDate = projectInitDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projectinfo.ProjectStatus
     *
     * @return the value of projectinfo.ProjectStatus
     *
     * @mbggenerated Sun Sep 28 21:58:29 CST 2014
     */
    public String getProjectStatus() {
        return projectStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projectinfo.ProjectStatus
     *
     * @param projectStatus the value for projectinfo.ProjectStatus
     *
     * @mbggenerated Sun Sep 28 21:58:29 CST 2014
     */
    public void setProjectStatus(String projectStatus) {
        this.projectStatus = projectStatus == null ? null : projectStatus.trim();
    }
}