package cn.org.hbca.project.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class ProjectinfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table projectinfo
     *
     * @mbggenerated Tue Nov 04 22:12:17 CST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table projectinfo
     *
     * @mbggenerated Tue Nov 04 22:12:17 CST 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table projectinfo
     *
     * @mbggenerated Tue Nov 04 22:12:17 CST 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projectinfo
     *
     * @mbggenerated Tue Nov 04 22:12:17 CST 2014
     */
    public ProjectinfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projectinfo
     *
     * @mbggenerated Tue Nov 04 22:12:17 CST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projectinfo
     *
     * @mbggenerated Tue Nov 04 22:12:17 CST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projectinfo
     *
     * @mbggenerated Tue Nov 04 22:12:17 CST 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projectinfo
     *
     * @mbggenerated Tue Nov 04 22:12:17 CST 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projectinfo
     *
     * @mbggenerated Tue Nov 04 22:12:17 CST 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projectinfo
     *
     * @mbggenerated Tue Nov 04 22:12:17 CST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projectinfo
     *
     * @mbggenerated Tue Nov 04 22:12:17 CST 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projectinfo
     *
     * @mbggenerated Tue Nov 04 22:12:17 CST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projectinfo
     *
     * @mbggenerated Tue Nov 04 22:12:17 CST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projectinfo
     *
     * @mbggenerated Tue Nov 04 22:12:17 CST 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table projectinfo
     *
     * @mbggenerated Tue Nov 04 22:12:17 CST 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andProjectIdIsNull() {
            addCriterion("ProjectId is null");
            return (Criteria) this;
        }

        public Criteria andProjectIdIsNotNull() {
            addCriterion("ProjectId is not null");
            return (Criteria) this;
        }

        public Criteria andProjectIdEqualTo(String value) {
            addCriterion("ProjectId =", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotEqualTo(String value) {
            addCriterion("ProjectId <>", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdGreaterThan(String value) {
            addCriterion("ProjectId >", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdGreaterThanOrEqualTo(String value) {
            addCriterion("ProjectId >=", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLessThan(String value) {
            addCriterion("ProjectId <", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLessThanOrEqualTo(String value) {
            addCriterion("ProjectId <=", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLike(String value) {
            addCriterion("ProjectId like", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotLike(String value) {
            addCriterion("ProjectId not like", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdIn(List<String> values) {
            addCriterion("ProjectId in", values, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotIn(List<String> values) {
            addCriterion("ProjectId not in", values, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdBetween(String value1, String value2) {
            addCriterion("ProjectId between", value1, value2, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotBetween(String value1, String value2) {
            addCriterion("ProjectId not between", value1, value2, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectNameIsNull() {
            addCriterion("ProjectName is null");
            return (Criteria) this;
        }

        public Criteria andProjectNameIsNotNull() {
            addCriterion("ProjectName is not null");
            return (Criteria) this;
        }

        public Criteria andProjectNameEqualTo(String value) {
            addCriterion("ProjectName =", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameNotEqualTo(String value) {
            addCriterion("ProjectName <>", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameGreaterThan(String value) {
            addCriterion("ProjectName >", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameGreaterThanOrEqualTo(String value) {
            addCriterion("ProjectName >=", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameLessThan(String value) {
            addCriterion("ProjectName <", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameLessThanOrEqualTo(String value) {
            addCriterion("ProjectName <=", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameLike(String value) {
            addCriterion("ProjectName like", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameNotLike(String value) {
            addCriterion("ProjectName not like", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameIn(List<String> values) {
            addCriterion("ProjectName in", values, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameNotIn(List<String> values) {
            addCriterion("ProjectName not in", values, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameBetween(String value1, String value2) {
            addCriterion("ProjectName between", value1, value2, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameNotBetween(String value1, String value2) {
            addCriterion("ProjectName not between", value1, value2, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectManagerIsNull() {
            addCriterion("ProjectManager is null");
            return (Criteria) this;
        }

        public Criteria andProjectManagerIsNotNull() {
            addCriterion("ProjectManager is not null");
            return (Criteria) this;
        }

        public Criteria andProjectManagerEqualTo(String value) {
            addCriterion("ProjectManager =", value, "projectManager");
            return (Criteria) this;
        }

        public Criteria andProjectManagerNotEqualTo(String value) {
            addCriterion("ProjectManager <>", value, "projectManager");
            return (Criteria) this;
        }

        public Criteria andProjectManagerGreaterThan(String value) {
            addCriterion("ProjectManager >", value, "projectManager");
            return (Criteria) this;
        }

        public Criteria andProjectManagerGreaterThanOrEqualTo(String value) {
            addCriterion("ProjectManager >=", value, "projectManager");
            return (Criteria) this;
        }

        public Criteria andProjectManagerLessThan(String value) {
            addCriterion("ProjectManager <", value, "projectManager");
            return (Criteria) this;
        }

        public Criteria andProjectManagerLessThanOrEqualTo(String value) {
            addCriterion("ProjectManager <=", value, "projectManager");
            return (Criteria) this;
        }

        public Criteria andProjectManagerLike(String value) {
            addCriterion("ProjectManager like", value, "projectManager");
            return (Criteria) this;
        }

        public Criteria andProjectManagerNotLike(String value) {
            addCriterion("ProjectManager not like", value, "projectManager");
            return (Criteria) this;
        }

        public Criteria andProjectManagerIn(List<String> values) {
            addCriterion("ProjectManager in", values, "projectManager");
            return (Criteria) this;
        }

        public Criteria andProjectManagerNotIn(List<String> values) {
            addCriterion("ProjectManager not in", values, "projectManager");
            return (Criteria) this;
        }

        public Criteria andProjectManagerBetween(String value1, String value2) {
            addCriterion("ProjectManager between", value1, value2, "projectManager");
            return (Criteria) this;
        }

        public Criteria andProjectManagerNotBetween(String value1, String value2) {
            addCriterion("ProjectManager not between", value1, value2, "projectManager");
            return (Criteria) this;
        }

        public Criteria andManufacturerNameIsNull() {
            addCriterion("ManufacturerName is null");
            return (Criteria) this;
        }

        public Criteria andManufacturerNameIsNotNull() {
            addCriterion("ManufacturerName is not null");
            return (Criteria) this;
        }

        public Criteria andManufacturerNameEqualTo(String value) {
            addCriterion("ManufacturerName =", value, "manufacturerName");
            return (Criteria) this;
        }

        public Criteria andManufacturerNameNotEqualTo(String value) {
            addCriterion("ManufacturerName <>", value, "manufacturerName");
            return (Criteria) this;
        }

        public Criteria andManufacturerNameGreaterThan(String value) {
            addCriterion("ManufacturerName >", value, "manufacturerName");
            return (Criteria) this;
        }

        public Criteria andManufacturerNameGreaterThanOrEqualTo(String value) {
            addCriterion("ManufacturerName >=", value, "manufacturerName");
            return (Criteria) this;
        }

        public Criteria andManufacturerNameLessThan(String value) {
            addCriterion("ManufacturerName <", value, "manufacturerName");
            return (Criteria) this;
        }

        public Criteria andManufacturerNameLessThanOrEqualTo(String value) {
            addCriterion("ManufacturerName <=", value, "manufacturerName");
            return (Criteria) this;
        }

        public Criteria andManufacturerNameLike(String value) {
            addCriterion("ManufacturerName like", value, "manufacturerName");
            return (Criteria) this;
        }

        public Criteria andManufacturerNameNotLike(String value) {
            addCriterion("ManufacturerName not like", value, "manufacturerName");
            return (Criteria) this;
        }

        public Criteria andManufacturerNameIn(List<String> values) {
            addCriterion("ManufacturerName in", values, "manufacturerName");
            return (Criteria) this;
        }

        public Criteria andManufacturerNameNotIn(List<String> values) {
            addCriterion("ManufacturerName not in", values, "manufacturerName");
            return (Criteria) this;
        }

        public Criteria andManufacturerNameBetween(String value1, String value2) {
            addCriterion("ManufacturerName between", value1, value2, "manufacturerName");
            return (Criteria) this;
        }

        public Criteria andManufacturerNameNotBetween(String value1, String value2) {
            addCriterion("ManufacturerName not between", value1, value2, "manufacturerName");
            return (Criteria) this;
        }

        public Criteria andManufacturerProjectNameIsNull() {
            addCriterion("ManufacturerProjectName is null");
            return (Criteria) this;
        }

        public Criteria andManufacturerProjectNameIsNotNull() {
            addCriterion("ManufacturerProjectName is not null");
            return (Criteria) this;
        }

        public Criteria andManufacturerProjectNameEqualTo(String value) {
            addCriterion("ManufacturerProjectName =", value, "manufacturerProjectName");
            return (Criteria) this;
        }

        public Criteria andManufacturerProjectNameNotEqualTo(String value) {
            addCriterion("ManufacturerProjectName <>", value, "manufacturerProjectName");
            return (Criteria) this;
        }

        public Criteria andManufacturerProjectNameGreaterThan(String value) {
            addCriterion("ManufacturerProjectName >", value, "manufacturerProjectName");
            return (Criteria) this;
        }

        public Criteria andManufacturerProjectNameGreaterThanOrEqualTo(String value) {
            addCriterion("ManufacturerProjectName >=", value, "manufacturerProjectName");
            return (Criteria) this;
        }

        public Criteria andManufacturerProjectNameLessThan(String value) {
            addCriterion("ManufacturerProjectName <", value, "manufacturerProjectName");
            return (Criteria) this;
        }

        public Criteria andManufacturerProjectNameLessThanOrEqualTo(String value) {
            addCriterion("ManufacturerProjectName <=", value, "manufacturerProjectName");
            return (Criteria) this;
        }

        public Criteria andManufacturerProjectNameLike(String value) {
            addCriterion("ManufacturerProjectName like", value, "manufacturerProjectName");
            return (Criteria) this;
        }

        public Criteria andManufacturerProjectNameNotLike(String value) {
            addCriterion("ManufacturerProjectName not like", value, "manufacturerProjectName");
            return (Criteria) this;
        }

        public Criteria andManufacturerProjectNameIn(List<String> values) {
            addCriterion("ManufacturerProjectName in", values, "manufacturerProjectName");
            return (Criteria) this;
        }

        public Criteria andManufacturerProjectNameNotIn(List<String> values) {
            addCriterion("ManufacturerProjectName not in", values, "manufacturerProjectName");
            return (Criteria) this;
        }

        public Criteria andManufacturerProjectNameBetween(String value1, String value2) {
            addCriterion("ManufacturerProjectName between", value1, value2, "manufacturerProjectName");
            return (Criteria) this;
        }

        public Criteria andManufacturerProjectNameNotBetween(String value1, String value2) {
            addCriterion("ManufacturerProjectName not between", value1, value2, "manufacturerProjectName");
            return (Criteria) this;
        }

        public Criteria andManufacturerProjectManagerIsNull() {
            addCriterion("ManufacturerProjectManager is null");
            return (Criteria) this;
        }

        public Criteria andManufacturerProjectManagerIsNotNull() {
            addCriterion("ManufacturerProjectManager is not null");
            return (Criteria) this;
        }

        public Criteria andManufacturerProjectManagerEqualTo(String value) {
            addCriterion("ManufacturerProjectManager =", value, "manufacturerProjectManager");
            return (Criteria) this;
        }

        public Criteria andManufacturerProjectManagerNotEqualTo(String value) {
            addCriterion("ManufacturerProjectManager <>", value, "manufacturerProjectManager");
            return (Criteria) this;
        }

        public Criteria andManufacturerProjectManagerGreaterThan(String value) {
            addCriterion("ManufacturerProjectManager >", value, "manufacturerProjectManager");
            return (Criteria) this;
        }

        public Criteria andManufacturerProjectManagerGreaterThanOrEqualTo(String value) {
            addCriterion("ManufacturerProjectManager >=", value, "manufacturerProjectManager");
            return (Criteria) this;
        }

        public Criteria andManufacturerProjectManagerLessThan(String value) {
            addCriterion("ManufacturerProjectManager <", value, "manufacturerProjectManager");
            return (Criteria) this;
        }

        public Criteria andManufacturerProjectManagerLessThanOrEqualTo(String value) {
            addCriterion("ManufacturerProjectManager <=", value, "manufacturerProjectManager");
            return (Criteria) this;
        }

        public Criteria andManufacturerProjectManagerLike(String value) {
            addCriterion("ManufacturerProjectManager like", value, "manufacturerProjectManager");
            return (Criteria) this;
        }

        public Criteria andManufacturerProjectManagerNotLike(String value) {
            addCriterion("ManufacturerProjectManager not like", value, "manufacturerProjectManager");
            return (Criteria) this;
        }

        public Criteria andManufacturerProjectManagerIn(List<String> values) {
            addCriterion("ManufacturerProjectManager in", values, "manufacturerProjectManager");
            return (Criteria) this;
        }

        public Criteria andManufacturerProjectManagerNotIn(List<String> values) {
            addCriterion("ManufacturerProjectManager not in", values, "manufacturerProjectManager");
            return (Criteria) this;
        }

        public Criteria andManufacturerProjectManagerBetween(String value1, String value2) {
            addCriterion("ManufacturerProjectManager between", value1, value2, "manufacturerProjectManager");
            return (Criteria) this;
        }

        public Criteria andManufacturerProjectManagerNotBetween(String value1, String value2) {
            addCriterion("ManufacturerProjectManager not between", value1, value2, "manufacturerProjectManager");
            return (Criteria) this;
        }

        public Criteria andManufacturerProjectDeveloperIsNull() {
            addCriterion("ManufacturerProjectDeveloper is null");
            return (Criteria) this;
        }

        public Criteria andManufacturerProjectDeveloperIsNotNull() {
            addCriterion("ManufacturerProjectDeveloper is not null");
            return (Criteria) this;
        }

        public Criteria andManufacturerProjectDeveloperEqualTo(String value) {
            addCriterion("ManufacturerProjectDeveloper =", value, "manufacturerProjectDeveloper");
            return (Criteria) this;
        }

        public Criteria andManufacturerProjectDeveloperNotEqualTo(String value) {
            addCriterion("ManufacturerProjectDeveloper <>", value, "manufacturerProjectDeveloper");
            return (Criteria) this;
        }

        public Criteria andManufacturerProjectDeveloperGreaterThan(String value) {
            addCriterion("ManufacturerProjectDeveloper >", value, "manufacturerProjectDeveloper");
            return (Criteria) this;
        }

        public Criteria andManufacturerProjectDeveloperGreaterThanOrEqualTo(String value) {
            addCriterion("ManufacturerProjectDeveloper >=", value, "manufacturerProjectDeveloper");
            return (Criteria) this;
        }

        public Criteria andManufacturerProjectDeveloperLessThan(String value) {
            addCriterion("ManufacturerProjectDeveloper <", value, "manufacturerProjectDeveloper");
            return (Criteria) this;
        }

        public Criteria andManufacturerProjectDeveloperLessThanOrEqualTo(String value) {
            addCriterion("ManufacturerProjectDeveloper <=", value, "manufacturerProjectDeveloper");
            return (Criteria) this;
        }

        public Criteria andManufacturerProjectDeveloperLike(String value) {
            addCriterion("ManufacturerProjectDeveloper like", value, "manufacturerProjectDeveloper");
            return (Criteria) this;
        }

        public Criteria andManufacturerProjectDeveloperNotLike(String value) {
            addCriterion("ManufacturerProjectDeveloper not like", value, "manufacturerProjectDeveloper");
            return (Criteria) this;
        }

        public Criteria andManufacturerProjectDeveloperIn(List<String> values) {
            addCriterion("ManufacturerProjectDeveloper in", values, "manufacturerProjectDeveloper");
            return (Criteria) this;
        }

        public Criteria andManufacturerProjectDeveloperNotIn(List<String> values) {
            addCriterion("ManufacturerProjectDeveloper not in", values, "manufacturerProjectDeveloper");
            return (Criteria) this;
        }

        public Criteria andManufacturerProjectDeveloperBetween(String value1, String value2) {
            addCriterion("ManufacturerProjectDeveloper between", value1, value2, "manufacturerProjectDeveloper");
            return (Criteria) this;
        }

        public Criteria andManufacturerProjectDeveloperNotBetween(String value1, String value2) {
            addCriterion("ManufacturerProjectDeveloper not between", value1, value2, "manufacturerProjectDeveloper");
            return (Criteria) this;
        }

        public Criteria andMPMContactIsNull() {
            addCriterion("MPMContact is null");
            return (Criteria) this;
        }

        public Criteria andMPMContactIsNotNull() {
            addCriterion("MPMContact is not null");
            return (Criteria) this;
        }

        public Criteria andMPMContactEqualTo(String value) {
            addCriterion("MPMContact =", value, "MPMContact");
            return (Criteria) this;
        }

        public Criteria andMPMContactNotEqualTo(String value) {
            addCriterion("MPMContact <>", value, "MPMContact");
            return (Criteria) this;
        }

        public Criteria andMPMContactGreaterThan(String value) {
            addCriterion("MPMContact >", value, "MPMContact");
            return (Criteria) this;
        }

        public Criteria andMPMContactGreaterThanOrEqualTo(String value) {
            addCriterion("MPMContact >=", value, "MPMContact");
            return (Criteria) this;
        }

        public Criteria andMPMContactLessThan(String value) {
            addCriterion("MPMContact <", value, "MPMContact");
            return (Criteria) this;
        }

        public Criteria andMPMContactLessThanOrEqualTo(String value) {
            addCriterion("MPMContact <=", value, "MPMContact");
            return (Criteria) this;
        }

        public Criteria andMPMContactLike(String value) {
            addCriterion("MPMContact like", value, "MPMContact");
            return (Criteria) this;
        }

        public Criteria andMPMContactNotLike(String value) {
            addCriterion("MPMContact not like", value, "MPMContact");
            return (Criteria) this;
        }

        public Criteria andMPMContactIn(List<String> values) {
            addCriterion("MPMContact in", values, "MPMContact");
            return (Criteria) this;
        }

        public Criteria andMPMContactNotIn(List<String> values) {
            addCriterion("MPMContact not in", values, "MPMContact");
            return (Criteria) this;
        }

        public Criteria andMPMContactBetween(String value1, String value2) {
            addCriterion("MPMContact between", value1, value2, "MPMContact");
            return (Criteria) this;
        }

        public Criteria andMPMContactNotBetween(String value1, String value2) {
            addCriterion("MPMContact not between", value1, value2, "MPMContact");
            return (Criteria) this;
        }

        public Criteria andMPDContactIsNull() {
            addCriterion("MPDContact is null");
            return (Criteria) this;
        }

        public Criteria andMPDContactIsNotNull() {
            addCriterion("MPDContact is not null");
            return (Criteria) this;
        }

        public Criteria andMPDContactEqualTo(String value) {
            addCriterion("MPDContact =", value, "MPDContact");
            return (Criteria) this;
        }

        public Criteria andMPDContactNotEqualTo(String value) {
            addCriterion("MPDContact <>", value, "MPDContact");
            return (Criteria) this;
        }

        public Criteria andMPDContactGreaterThan(String value) {
            addCriterion("MPDContact >", value, "MPDContact");
            return (Criteria) this;
        }

        public Criteria andMPDContactGreaterThanOrEqualTo(String value) {
            addCriterion("MPDContact >=", value, "MPDContact");
            return (Criteria) this;
        }

        public Criteria andMPDContactLessThan(String value) {
            addCriterion("MPDContact <", value, "MPDContact");
            return (Criteria) this;
        }

        public Criteria andMPDContactLessThanOrEqualTo(String value) {
            addCriterion("MPDContact <=", value, "MPDContact");
            return (Criteria) this;
        }

        public Criteria andMPDContactLike(String value) {
            addCriterion("MPDContact like", value, "MPDContact");
            return (Criteria) this;
        }

        public Criteria andMPDContactNotLike(String value) {
            addCriterion("MPDContact not like", value, "MPDContact");
            return (Criteria) this;
        }

        public Criteria andMPDContactIn(List<String> values) {
            addCriterion("MPDContact in", values, "MPDContact");
            return (Criteria) this;
        }

        public Criteria andMPDContactNotIn(List<String> values) {
            addCriterion("MPDContact not in", values, "MPDContact");
            return (Criteria) this;
        }

        public Criteria andMPDContactBetween(String value1, String value2) {
            addCriterion("MPDContact between", value1, value2, "MPDContact");
            return (Criteria) this;
        }

        public Criteria andMPDContactNotBetween(String value1, String value2) {
            addCriterion("MPDContact not between", value1, value2, "MPDContact");
            return (Criteria) this;
        }

        public Criteria andPlanDevStartDateIsNull() {
            addCriterion("PlanDevStartDate is null");
            return (Criteria) this;
        }

        public Criteria andPlanDevStartDateIsNotNull() {
            addCriterion("PlanDevStartDate is not null");
            return (Criteria) this;
        }

        public Criteria andPlanDevStartDateEqualTo(Date value) {
            addCriterionForJDBCDate("PlanDevStartDate =", value, "planDevStartDate");
            return (Criteria) this;
        }

        public Criteria andPlanDevStartDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("PlanDevStartDate <>", value, "planDevStartDate");
            return (Criteria) this;
        }

        public Criteria andPlanDevStartDateGreaterThan(Date value) {
            addCriterionForJDBCDate("PlanDevStartDate >", value, "planDevStartDate");
            return (Criteria) this;
        }

        public Criteria andPlanDevStartDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("PlanDevStartDate >=", value, "planDevStartDate");
            return (Criteria) this;
        }

        public Criteria andPlanDevStartDateLessThan(Date value) {
            addCriterionForJDBCDate("PlanDevStartDate <", value, "planDevStartDate");
            return (Criteria) this;
        }

        public Criteria andPlanDevStartDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("PlanDevStartDate <=", value, "planDevStartDate");
            return (Criteria) this;
        }

        public Criteria andPlanDevStartDateIn(List<Date> values) {
            addCriterionForJDBCDate("PlanDevStartDate in", values, "planDevStartDate");
            return (Criteria) this;
        }

        public Criteria andPlanDevStartDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("PlanDevStartDate not in", values, "planDevStartDate");
            return (Criteria) this;
        }

        public Criteria andPlanDevStartDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("PlanDevStartDate between", value1, value2, "planDevStartDate");
            return (Criteria) this;
        }

        public Criteria andPlanDevStartDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("PlanDevStartDate not between", value1, value2, "planDevStartDate");
            return (Criteria) this;
        }

        public Criteria andActualDevStartDateIsNull() {
            addCriterion("ActualDevStartDate is null");
            return (Criteria) this;
        }

        public Criteria andActualDevStartDateIsNotNull() {
            addCriterion("ActualDevStartDate is not null");
            return (Criteria) this;
        }

        public Criteria andActualDevStartDateEqualTo(Date value) {
            addCriterionForJDBCDate("ActualDevStartDate =", value, "actualDevStartDate");
            return (Criteria) this;
        }

        public Criteria andActualDevStartDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("ActualDevStartDate <>", value, "actualDevStartDate");
            return (Criteria) this;
        }

        public Criteria andActualDevStartDateGreaterThan(Date value) {
            addCriterionForJDBCDate("ActualDevStartDate >", value, "actualDevStartDate");
            return (Criteria) this;
        }

        public Criteria andActualDevStartDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("ActualDevStartDate >=", value, "actualDevStartDate");
            return (Criteria) this;
        }

        public Criteria andActualDevStartDateLessThan(Date value) {
            addCriterionForJDBCDate("ActualDevStartDate <", value, "actualDevStartDate");
            return (Criteria) this;
        }

        public Criteria andActualDevStartDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("ActualDevStartDate <=", value, "actualDevStartDate");
            return (Criteria) this;
        }

        public Criteria andActualDevStartDateIn(List<Date> values) {
            addCriterionForJDBCDate("ActualDevStartDate in", values, "actualDevStartDate");
            return (Criteria) this;
        }

        public Criteria andActualDevStartDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("ActualDevStartDate not in", values, "actualDevStartDate");
            return (Criteria) this;
        }

        public Criteria andActualDevStartDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("ActualDevStartDate between", value1, value2, "actualDevStartDate");
            return (Criteria) this;
        }

        public Criteria andActualDevStartDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("ActualDevStartDate not between", value1, value2, "actualDevStartDate");
            return (Criteria) this;
        }

        public Criteria andPlanAcceptDateIsNull() {
            addCriterion("PlanAcceptDate is null");
            return (Criteria) this;
        }

        public Criteria andPlanAcceptDateIsNotNull() {
            addCriterion("PlanAcceptDate is not null");
            return (Criteria) this;
        }

        public Criteria andPlanAcceptDateEqualTo(Date value) {
            addCriterionForJDBCDate("PlanAcceptDate =", value, "planAcceptDate");
            return (Criteria) this;
        }

        public Criteria andPlanAcceptDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("PlanAcceptDate <>", value, "planAcceptDate");
            return (Criteria) this;
        }

        public Criteria andPlanAcceptDateGreaterThan(Date value) {
            addCriterionForJDBCDate("PlanAcceptDate >", value, "planAcceptDate");
            return (Criteria) this;
        }

        public Criteria andPlanAcceptDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("PlanAcceptDate >=", value, "planAcceptDate");
            return (Criteria) this;
        }

        public Criteria andPlanAcceptDateLessThan(Date value) {
            addCriterionForJDBCDate("PlanAcceptDate <", value, "planAcceptDate");
            return (Criteria) this;
        }

        public Criteria andPlanAcceptDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("PlanAcceptDate <=", value, "planAcceptDate");
            return (Criteria) this;
        }

        public Criteria andPlanAcceptDateIn(List<Date> values) {
            addCriterionForJDBCDate("PlanAcceptDate in", values, "planAcceptDate");
            return (Criteria) this;
        }

        public Criteria andPlanAcceptDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("PlanAcceptDate not in", values, "planAcceptDate");
            return (Criteria) this;
        }

        public Criteria andPlanAcceptDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("PlanAcceptDate between", value1, value2, "planAcceptDate");
            return (Criteria) this;
        }

        public Criteria andPlanAcceptDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("PlanAcceptDate not between", value1, value2, "planAcceptDate");
            return (Criteria) this;
        }

        public Criteria andActualAcceptDateIsNull() {
            addCriterion("ActualAcceptDate is null");
            return (Criteria) this;
        }

        public Criteria andActualAcceptDateIsNotNull() {
            addCriterion("ActualAcceptDate is not null");
            return (Criteria) this;
        }

        public Criteria andActualAcceptDateEqualTo(Date value) {
            addCriterionForJDBCDate("ActualAcceptDate =", value, "actualAcceptDate");
            return (Criteria) this;
        }

        public Criteria andActualAcceptDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("ActualAcceptDate <>", value, "actualAcceptDate");
            return (Criteria) this;
        }

        public Criteria andActualAcceptDateGreaterThan(Date value) {
            addCriterionForJDBCDate("ActualAcceptDate >", value, "actualAcceptDate");
            return (Criteria) this;
        }

        public Criteria andActualAcceptDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("ActualAcceptDate >=", value, "actualAcceptDate");
            return (Criteria) this;
        }

        public Criteria andActualAcceptDateLessThan(Date value) {
            addCriterionForJDBCDate("ActualAcceptDate <", value, "actualAcceptDate");
            return (Criteria) this;
        }

        public Criteria andActualAcceptDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("ActualAcceptDate <=", value, "actualAcceptDate");
            return (Criteria) this;
        }

        public Criteria andActualAcceptDateIn(List<Date> values) {
            addCriterionForJDBCDate("ActualAcceptDate in", values, "actualAcceptDate");
            return (Criteria) this;
        }

        public Criteria andActualAcceptDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("ActualAcceptDate not in", values, "actualAcceptDate");
            return (Criteria) this;
        }

        public Criteria andActualAcceptDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("ActualAcceptDate between", value1, value2, "actualAcceptDate");
            return (Criteria) this;
        }

        public Criteria andActualAcceptDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("ActualAcceptDate not between", value1, value2, "actualAcceptDate");
            return (Criteria) this;
        }

        public Criteria andDevTechIsNull() {
            addCriterion("DevTech is null");
            return (Criteria) this;
        }

        public Criteria andDevTechIsNotNull() {
            addCriterion("DevTech is not null");
            return (Criteria) this;
        }

        public Criteria andDevTechEqualTo(String value) {
            addCriterion("DevTech =", value, "devTech");
            return (Criteria) this;
        }

        public Criteria andDevTechNotEqualTo(String value) {
            addCriterion("DevTech <>", value, "devTech");
            return (Criteria) this;
        }

        public Criteria andDevTechGreaterThan(String value) {
            addCriterion("DevTech >", value, "devTech");
            return (Criteria) this;
        }

        public Criteria andDevTechGreaterThanOrEqualTo(String value) {
            addCriterion("DevTech >=", value, "devTech");
            return (Criteria) this;
        }

        public Criteria andDevTechLessThan(String value) {
            addCriterion("DevTech <", value, "devTech");
            return (Criteria) this;
        }

        public Criteria andDevTechLessThanOrEqualTo(String value) {
            addCriterion("DevTech <=", value, "devTech");
            return (Criteria) this;
        }

        public Criteria andDevTechLike(String value) {
            addCriterion("DevTech like", value, "devTech");
            return (Criteria) this;
        }

        public Criteria andDevTechNotLike(String value) {
            addCriterion("DevTech not like", value, "devTech");
            return (Criteria) this;
        }

        public Criteria andDevTechIn(List<String> values) {
            addCriterion("DevTech in", values, "devTech");
            return (Criteria) this;
        }

        public Criteria andDevTechNotIn(List<String> values) {
            addCriterion("DevTech not in", values, "devTech");
            return (Criteria) this;
        }

        public Criteria andDevTechBetween(String value1, String value2) {
            addCriterion("DevTech between", value1, value2, "devTech");
            return (Criteria) this;
        }

        public Criteria andDevTechNotBetween(String value1, String value2) {
            addCriterion("DevTech not between", value1, value2, "devTech");
            return (Criteria) this;
        }

        public Criteria andNetWorkEnvironmentIsNull() {
            addCriterion("NetWorkEnvironment is null");
            return (Criteria) this;
        }

        public Criteria andNetWorkEnvironmentIsNotNull() {
            addCriterion("NetWorkEnvironment is not null");
            return (Criteria) this;
        }

        public Criteria andNetWorkEnvironmentEqualTo(String value) {
            addCriterion("NetWorkEnvironment =", value, "netWorkEnvironment");
            return (Criteria) this;
        }

        public Criteria andNetWorkEnvironmentNotEqualTo(String value) {
            addCriterion("NetWorkEnvironment <>", value, "netWorkEnvironment");
            return (Criteria) this;
        }

        public Criteria andNetWorkEnvironmentGreaterThan(String value) {
            addCriterion("NetWorkEnvironment >", value, "netWorkEnvironment");
            return (Criteria) this;
        }

        public Criteria andNetWorkEnvironmentGreaterThanOrEqualTo(String value) {
            addCriterion("NetWorkEnvironment >=", value, "netWorkEnvironment");
            return (Criteria) this;
        }

        public Criteria andNetWorkEnvironmentLessThan(String value) {
            addCriterion("NetWorkEnvironment <", value, "netWorkEnvironment");
            return (Criteria) this;
        }

        public Criteria andNetWorkEnvironmentLessThanOrEqualTo(String value) {
            addCriterion("NetWorkEnvironment <=", value, "netWorkEnvironment");
            return (Criteria) this;
        }

        public Criteria andNetWorkEnvironmentLike(String value) {
            addCriterion("NetWorkEnvironment like", value, "netWorkEnvironment");
            return (Criteria) this;
        }

        public Criteria andNetWorkEnvironmentNotLike(String value) {
            addCriterion("NetWorkEnvironment not like", value, "netWorkEnvironment");
            return (Criteria) this;
        }

        public Criteria andNetWorkEnvironmentIn(List<String> values) {
            addCriterion("NetWorkEnvironment in", values, "netWorkEnvironment");
            return (Criteria) this;
        }

        public Criteria andNetWorkEnvironmentNotIn(List<String> values) {
            addCriterion("NetWorkEnvironment not in", values, "netWorkEnvironment");
            return (Criteria) this;
        }

        public Criteria andNetWorkEnvironmentBetween(String value1, String value2) {
            addCriterion("NetWorkEnvironment between", value1, value2, "netWorkEnvironment");
            return (Criteria) this;
        }

        public Criteria andNetWorkEnvironmentNotBetween(String value1, String value2) {
            addCriterion("NetWorkEnvironment not between", value1, value2, "netWorkEnvironment");
            return (Criteria) this;
        }

        public Criteria andServerEnvironmentIsNull() {
            addCriterion("ServerEnvironment is null");
            return (Criteria) this;
        }

        public Criteria andServerEnvironmentIsNotNull() {
            addCriterion("ServerEnvironment is not null");
            return (Criteria) this;
        }

        public Criteria andServerEnvironmentEqualTo(String value) {
            addCriterion("ServerEnvironment =", value, "serverEnvironment");
            return (Criteria) this;
        }

        public Criteria andServerEnvironmentNotEqualTo(String value) {
            addCriterion("ServerEnvironment <>", value, "serverEnvironment");
            return (Criteria) this;
        }

        public Criteria andServerEnvironmentGreaterThan(String value) {
            addCriterion("ServerEnvironment >", value, "serverEnvironment");
            return (Criteria) this;
        }

        public Criteria andServerEnvironmentGreaterThanOrEqualTo(String value) {
            addCriterion("ServerEnvironment >=", value, "serverEnvironment");
            return (Criteria) this;
        }

        public Criteria andServerEnvironmentLessThan(String value) {
            addCriterion("ServerEnvironment <", value, "serverEnvironment");
            return (Criteria) this;
        }

        public Criteria andServerEnvironmentLessThanOrEqualTo(String value) {
            addCriterion("ServerEnvironment <=", value, "serverEnvironment");
            return (Criteria) this;
        }

        public Criteria andServerEnvironmentLike(String value) {
            addCriterion("ServerEnvironment like", value, "serverEnvironment");
            return (Criteria) this;
        }

        public Criteria andServerEnvironmentNotLike(String value) {
            addCriterion("ServerEnvironment not like", value, "serverEnvironment");
            return (Criteria) this;
        }

        public Criteria andServerEnvironmentIn(List<String> values) {
            addCriterion("ServerEnvironment in", values, "serverEnvironment");
            return (Criteria) this;
        }

        public Criteria andServerEnvironmentNotIn(List<String> values) {
            addCriterion("ServerEnvironment not in", values, "serverEnvironment");
            return (Criteria) this;
        }

        public Criteria andServerEnvironmentBetween(String value1, String value2) {
            addCriterion("ServerEnvironment between", value1, value2, "serverEnvironment");
            return (Criteria) this;
        }

        public Criteria andServerEnvironmentNotBetween(String value1, String value2) {
            addCriterion("ServerEnvironment not between", value1, value2, "serverEnvironment");
            return (Criteria) this;
        }

        public Criteria andClientEnvironmentIsNull() {
            addCriterion("ClientEnvironment is null");
            return (Criteria) this;
        }

        public Criteria andClientEnvironmentIsNotNull() {
            addCriterion("ClientEnvironment is not null");
            return (Criteria) this;
        }

        public Criteria andClientEnvironmentEqualTo(String value) {
            addCriterion("ClientEnvironment =", value, "clientEnvironment");
            return (Criteria) this;
        }

        public Criteria andClientEnvironmentNotEqualTo(String value) {
            addCriterion("ClientEnvironment <>", value, "clientEnvironment");
            return (Criteria) this;
        }

        public Criteria andClientEnvironmentGreaterThan(String value) {
            addCriterion("ClientEnvironment >", value, "clientEnvironment");
            return (Criteria) this;
        }

        public Criteria andClientEnvironmentGreaterThanOrEqualTo(String value) {
            addCriterion("ClientEnvironment >=", value, "clientEnvironment");
            return (Criteria) this;
        }

        public Criteria andClientEnvironmentLessThan(String value) {
            addCriterion("ClientEnvironment <", value, "clientEnvironment");
            return (Criteria) this;
        }

        public Criteria andClientEnvironmentLessThanOrEqualTo(String value) {
            addCriterion("ClientEnvironment <=", value, "clientEnvironment");
            return (Criteria) this;
        }

        public Criteria andClientEnvironmentLike(String value) {
            addCriterion("ClientEnvironment like", value, "clientEnvironment");
            return (Criteria) this;
        }

        public Criteria andClientEnvironmentNotLike(String value) {
            addCriterion("ClientEnvironment not like", value, "clientEnvironment");
            return (Criteria) this;
        }

        public Criteria andClientEnvironmentIn(List<String> values) {
            addCriterion("ClientEnvironment in", values, "clientEnvironment");
            return (Criteria) this;
        }

        public Criteria andClientEnvironmentNotIn(List<String> values) {
            addCriterion("ClientEnvironment not in", values, "clientEnvironment");
            return (Criteria) this;
        }

        public Criteria andClientEnvironmentBetween(String value1, String value2) {
            addCriterion("ClientEnvironment between", value1, value2, "clientEnvironment");
            return (Criteria) this;
        }

        public Criteria andClientEnvironmentNotBetween(String value1, String value2) {
            addCriterion("ClientEnvironment not between", value1, value2, "clientEnvironment");
            return (Criteria) this;
        }

        public Criteria andOtherEnvironmentIsNull() {
            addCriterion("OtherEnvironment is null");
            return (Criteria) this;
        }

        public Criteria andOtherEnvironmentIsNotNull() {
            addCriterion("OtherEnvironment is not null");
            return (Criteria) this;
        }

        public Criteria andOtherEnvironmentEqualTo(String value) {
            addCriterion("OtherEnvironment =", value, "otherEnvironment");
            return (Criteria) this;
        }

        public Criteria andOtherEnvironmentNotEqualTo(String value) {
            addCriterion("OtherEnvironment <>", value, "otherEnvironment");
            return (Criteria) this;
        }

        public Criteria andOtherEnvironmentGreaterThan(String value) {
            addCriterion("OtherEnvironment >", value, "otherEnvironment");
            return (Criteria) this;
        }

        public Criteria andOtherEnvironmentGreaterThanOrEqualTo(String value) {
            addCriterion("OtherEnvironment >=", value, "otherEnvironment");
            return (Criteria) this;
        }

        public Criteria andOtherEnvironmentLessThan(String value) {
            addCriterion("OtherEnvironment <", value, "otherEnvironment");
            return (Criteria) this;
        }

        public Criteria andOtherEnvironmentLessThanOrEqualTo(String value) {
            addCriterion("OtherEnvironment <=", value, "otherEnvironment");
            return (Criteria) this;
        }

        public Criteria andOtherEnvironmentLike(String value) {
            addCriterion("OtherEnvironment like", value, "otherEnvironment");
            return (Criteria) this;
        }

        public Criteria andOtherEnvironmentNotLike(String value) {
            addCriterion("OtherEnvironment not like", value, "otherEnvironment");
            return (Criteria) this;
        }

        public Criteria andOtherEnvironmentIn(List<String> values) {
            addCriterion("OtherEnvironment in", values, "otherEnvironment");
            return (Criteria) this;
        }

        public Criteria andOtherEnvironmentNotIn(List<String> values) {
            addCriterion("OtherEnvironment not in", values, "otherEnvironment");
            return (Criteria) this;
        }

        public Criteria andOtherEnvironmentBetween(String value1, String value2) {
            addCriterion("OtherEnvironment between", value1, value2, "otherEnvironment");
            return (Criteria) this;
        }

        public Criteria andOtherEnvironmentNotBetween(String value1, String value2) {
            addCriterion("OtherEnvironment not between", value1, value2, "otherEnvironment");
            return (Criteria) this;
        }

        public Criteria andFunctionsNeededIntegrateIsNull() {
            addCriterion("FunctionsNeededIntegrate is null");
            return (Criteria) this;
        }

        public Criteria andFunctionsNeededIntegrateIsNotNull() {
            addCriterion("FunctionsNeededIntegrate is not null");
            return (Criteria) this;
        }

        public Criteria andFunctionsNeededIntegrateEqualTo(String value) {
            addCriterion("FunctionsNeededIntegrate =", value, "functionsNeededIntegrate");
            return (Criteria) this;
        }

        public Criteria andFunctionsNeededIntegrateNotEqualTo(String value) {
            addCriterion("FunctionsNeededIntegrate <>", value, "functionsNeededIntegrate");
            return (Criteria) this;
        }

        public Criteria andFunctionsNeededIntegrateGreaterThan(String value) {
            addCriterion("FunctionsNeededIntegrate >", value, "functionsNeededIntegrate");
            return (Criteria) this;
        }

        public Criteria andFunctionsNeededIntegrateGreaterThanOrEqualTo(String value) {
            addCriterion("FunctionsNeededIntegrate >=", value, "functionsNeededIntegrate");
            return (Criteria) this;
        }

        public Criteria andFunctionsNeededIntegrateLessThan(String value) {
            addCriterion("FunctionsNeededIntegrate <", value, "functionsNeededIntegrate");
            return (Criteria) this;
        }

        public Criteria andFunctionsNeededIntegrateLessThanOrEqualTo(String value) {
            addCriterion("FunctionsNeededIntegrate <=", value, "functionsNeededIntegrate");
            return (Criteria) this;
        }

        public Criteria andFunctionsNeededIntegrateLike(String value) {
            addCriterion("FunctionsNeededIntegrate like", value, "functionsNeededIntegrate");
            return (Criteria) this;
        }

        public Criteria andFunctionsNeededIntegrateNotLike(String value) {
            addCriterion("FunctionsNeededIntegrate not like", value, "functionsNeededIntegrate");
            return (Criteria) this;
        }

        public Criteria andFunctionsNeededIntegrateIn(List<String> values) {
            addCriterion("FunctionsNeededIntegrate in", values, "functionsNeededIntegrate");
            return (Criteria) this;
        }

        public Criteria andFunctionsNeededIntegrateNotIn(List<String> values) {
            addCriterion("FunctionsNeededIntegrate not in", values, "functionsNeededIntegrate");
            return (Criteria) this;
        }

        public Criteria andFunctionsNeededIntegrateBetween(String value1, String value2) {
            addCriterion("FunctionsNeededIntegrate between", value1, value2, "functionsNeededIntegrate");
            return (Criteria) this;
        }

        public Criteria andFunctionsNeededIntegrateNotBetween(String value1, String value2) {
            addCriterion("FunctionsNeededIntegrate not between", value1, value2, "functionsNeededIntegrate");
            return (Criteria) this;
        }

        public Criteria andProjectCodeIsNull() {
            addCriterion("ProjectCode is null");
            return (Criteria) this;
        }

        public Criteria andProjectCodeIsNotNull() {
            addCriterion("ProjectCode is not null");
            return (Criteria) this;
        }

        public Criteria andProjectCodeEqualTo(String value) {
            addCriterion("ProjectCode =", value, "projectCode");
            return (Criteria) this;
        }

        public Criteria andProjectCodeNotEqualTo(String value) {
            addCriterion("ProjectCode <>", value, "projectCode");
            return (Criteria) this;
        }

        public Criteria andProjectCodeGreaterThan(String value) {
            addCriterion("ProjectCode >", value, "projectCode");
            return (Criteria) this;
        }

        public Criteria andProjectCodeGreaterThanOrEqualTo(String value) {
            addCriterion("ProjectCode >=", value, "projectCode");
            return (Criteria) this;
        }

        public Criteria andProjectCodeLessThan(String value) {
            addCriterion("ProjectCode <", value, "projectCode");
            return (Criteria) this;
        }

        public Criteria andProjectCodeLessThanOrEqualTo(String value) {
            addCriterion("ProjectCode <=", value, "projectCode");
            return (Criteria) this;
        }

        public Criteria andProjectCodeLike(String value) {
            addCriterion("ProjectCode like", value, "projectCode");
            return (Criteria) this;
        }

        public Criteria andProjectCodeNotLike(String value) {
            addCriterion("ProjectCode not like", value, "projectCode");
            return (Criteria) this;
        }

        public Criteria andProjectCodeIn(List<String> values) {
            addCriterion("ProjectCode in", values, "projectCode");
            return (Criteria) this;
        }

        public Criteria andProjectCodeNotIn(List<String> values) {
            addCriterion("ProjectCode not in", values, "projectCode");
            return (Criteria) this;
        }

        public Criteria andProjectCodeBetween(String value1, String value2) {
            addCriterion("ProjectCode between", value1, value2, "projectCode");
            return (Criteria) this;
        }

        public Criteria andProjectCodeNotBetween(String value1, String value2) {
            addCriterion("ProjectCode not between", value1, value2, "projectCode");
            return (Criteria) this;
        }

        public Criteria andIncreaseIssueIsNull() {
            addCriterion("IncreaseIssue is null");
            return (Criteria) this;
        }

        public Criteria andIncreaseIssueIsNotNull() {
            addCriterion("IncreaseIssue is not null");
            return (Criteria) this;
        }

        public Criteria andIncreaseIssueEqualTo(String value) {
            addCriterion("IncreaseIssue =", value, "increaseIssue");
            return (Criteria) this;
        }

        public Criteria andIncreaseIssueNotEqualTo(String value) {
            addCriterion("IncreaseIssue <>", value, "increaseIssue");
            return (Criteria) this;
        }

        public Criteria andIncreaseIssueGreaterThan(String value) {
            addCriterion("IncreaseIssue >", value, "increaseIssue");
            return (Criteria) this;
        }

        public Criteria andIncreaseIssueGreaterThanOrEqualTo(String value) {
            addCriterion("IncreaseIssue >=", value, "increaseIssue");
            return (Criteria) this;
        }

        public Criteria andIncreaseIssueLessThan(String value) {
            addCriterion("IncreaseIssue <", value, "increaseIssue");
            return (Criteria) this;
        }

        public Criteria andIncreaseIssueLessThanOrEqualTo(String value) {
            addCriterion("IncreaseIssue <=", value, "increaseIssue");
            return (Criteria) this;
        }

        public Criteria andIncreaseIssueLike(String value) {
            addCriterion("IncreaseIssue like", value, "increaseIssue");
            return (Criteria) this;
        }

        public Criteria andIncreaseIssueNotLike(String value) {
            addCriterion("IncreaseIssue not like", value, "increaseIssue");
            return (Criteria) this;
        }

        public Criteria andIncreaseIssueIn(List<String> values) {
            addCriterion("IncreaseIssue in", values, "increaseIssue");
            return (Criteria) this;
        }

        public Criteria andIncreaseIssueNotIn(List<String> values) {
            addCriterion("IncreaseIssue not in", values, "increaseIssue");
            return (Criteria) this;
        }

        public Criteria andIncreaseIssueBetween(String value1, String value2) {
            addCriterion("IncreaseIssue between", value1, value2, "increaseIssue");
            return (Criteria) this;
        }

        public Criteria andIncreaseIssueNotBetween(String value1, String value2) {
            addCriterion("IncreaseIssue not between", value1, value2, "increaseIssue");
            return (Criteria) this;
        }

        public Criteria andEncryptFileLimitIsNull() {
            addCriterion("EncryptFileLimit is null");
            return (Criteria) this;
        }

        public Criteria andEncryptFileLimitIsNotNull() {
            addCriterion("EncryptFileLimit is not null");
            return (Criteria) this;
        }

        public Criteria andEncryptFileLimitEqualTo(String value) {
            addCriterion("EncryptFileLimit =", value, "encryptFileLimit");
            return (Criteria) this;
        }

        public Criteria andEncryptFileLimitNotEqualTo(String value) {
            addCriterion("EncryptFileLimit <>", value, "encryptFileLimit");
            return (Criteria) this;
        }

        public Criteria andEncryptFileLimitGreaterThan(String value) {
            addCriterion("EncryptFileLimit >", value, "encryptFileLimit");
            return (Criteria) this;
        }

        public Criteria andEncryptFileLimitGreaterThanOrEqualTo(String value) {
            addCriterion("EncryptFileLimit >=", value, "encryptFileLimit");
            return (Criteria) this;
        }

        public Criteria andEncryptFileLimitLessThan(String value) {
            addCriterion("EncryptFileLimit <", value, "encryptFileLimit");
            return (Criteria) this;
        }

        public Criteria andEncryptFileLimitLessThanOrEqualTo(String value) {
            addCriterion("EncryptFileLimit <=", value, "encryptFileLimit");
            return (Criteria) this;
        }

        public Criteria andEncryptFileLimitLike(String value) {
            addCriterion("EncryptFileLimit like", value, "encryptFileLimit");
            return (Criteria) this;
        }

        public Criteria andEncryptFileLimitNotLike(String value) {
            addCriterion("EncryptFileLimit not like", value, "encryptFileLimit");
            return (Criteria) this;
        }

        public Criteria andEncryptFileLimitIn(List<String> values) {
            addCriterion("EncryptFileLimit in", values, "encryptFileLimit");
            return (Criteria) this;
        }

        public Criteria andEncryptFileLimitNotIn(List<String> values) {
            addCriterion("EncryptFileLimit not in", values, "encryptFileLimit");
            return (Criteria) this;
        }

        public Criteria andEncryptFileLimitBetween(String value1, String value2) {
            addCriterion("EncryptFileLimit between", value1, value2, "encryptFileLimit");
            return (Criteria) this;
        }

        public Criteria andEncryptFileLimitNotBetween(String value1, String value2) {
            addCriterion("EncryptFileLimit not between", value1, value2, "encryptFileLimit");
            return (Criteria) this;
        }

        public Criteria andKeepEncryptKeyIsNull() {
            addCriterion("KeepEncryptKey is null");
            return (Criteria) this;
        }

        public Criteria andKeepEncryptKeyIsNotNull() {
            addCriterion("KeepEncryptKey is not null");
            return (Criteria) this;
        }

        public Criteria andKeepEncryptKeyEqualTo(Boolean value) {
            addCriterion("KeepEncryptKey =", value, "keepEncryptKey");
            return (Criteria) this;
        }

        public Criteria andKeepEncryptKeyNotEqualTo(Boolean value) {
            addCriterion("KeepEncryptKey <>", value, "keepEncryptKey");
            return (Criteria) this;
        }

        public Criteria andKeepEncryptKeyGreaterThan(Boolean value) {
            addCriterion("KeepEncryptKey >", value, "keepEncryptKey");
            return (Criteria) this;
        }

        public Criteria andKeepEncryptKeyGreaterThanOrEqualTo(Boolean value) {
            addCriterion("KeepEncryptKey >=", value, "keepEncryptKey");
            return (Criteria) this;
        }

        public Criteria andKeepEncryptKeyLessThan(Boolean value) {
            addCriterion("KeepEncryptKey <", value, "keepEncryptKey");
            return (Criteria) this;
        }

        public Criteria andKeepEncryptKeyLessThanOrEqualTo(Boolean value) {
            addCriterion("KeepEncryptKey <=", value, "keepEncryptKey");
            return (Criteria) this;
        }

        public Criteria andKeepEncryptKeyIn(List<Boolean> values) {
            addCriterion("KeepEncryptKey in", values, "keepEncryptKey");
            return (Criteria) this;
        }

        public Criteria andKeepEncryptKeyNotIn(List<Boolean> values) {
            addCriterion("KeepEncryptKey not in", values, "keepEncryptKey");
            return (Criteria) this;
        }

        public Criteria andKeepEncryptKeyBetween(Boolean value1, Boolean value2) {
            addCriterion("KeepEncryptKey between", value1, value2, "keepEncryptKey");
            return (Criteria) this;
        }

        public Criteria andKeepEncryptKeyNotBetween(Boolean value1, Boolean value2) {
            addCriterion("KeepEncryptKey not between", value1, value2, "keepEncryptKey");
            return (Criteria) this;
        }

        public Criteria andMultiOperationIsNull() {
            addCriterion("MultiOperation is null");
            return (Criteria) this;
        }

        public Criteria andMultiOperationIsNotNull() {
            addCriterion("MultiOperation is not null");
            return (Criteria) this;
        }

        public Criteria andMultiOperationEqualTo(String value) {
            addCriterion("MultiOperation =", value, "multiOperation");
            return (Criteria) this;
        }

        public Criteria andMultiOperationNotEqualTo(String value) {
            addCriterion("MultiOperation <>", value, "multiOperation");
            return (Criteria) this;
        }

        public Criteria andMultiOperationGreaterThan(String value) {
            addCriterion("MultiOperation >", value, "multiOperation");
            return (Criteria) this;
        }

        public Criteria andMultiOperationGreaterThanOrEqualTo(String value) {
            addCriterion("MultiOperation >=", value, "multiOperation");
            return (Criteria) this;
        }

        public Criteria andMultiOperationLessThan(String value) {
            addCriterion("MultiOperation <", value, "multiOperation");
            return (Criteria) this;
        }

        public Criteria andMultiOperationLessThanOrEqualTo(String value) {
            addCriterion("MultiOperation <=", value, "multiOperation");
            return (Criteria) this;
        }

        public Criteria andMultiOperationLike(String value) {
            addCriterion("MultiOperation like", value, "multiOperation");
            return (Criteria) this;
        }

        public Criteria andMultiOperationNotLike(String value) {
            addCriterion("MultiOperation not like", value, "multiOperation");
            return (Criteria) this;
        }

        public Criteria andMultiOperationIn(List<String> values) {
            addCriterion("MultiOperation in", values, "multiOperation");
            return (Criteria) this;
        }

        public Criteria andMultiOperationNotIn(List<String> values) {
            addCriterion("MultiOperation not in", values, "multiOperation");
            return (Criteria) this;
        }

        public Criteria andMultiOperationBetween(String value1, String value2) {
            addCriterion("MultiOperation between", value1, value2, "multiOperation");
            return (Criteria) this;
        }

        public Criteria andMultiOperationNotBetween(String value1, String value2) {
            addCriterion("MultiOperation not between", value1, value2, "multiOperation");
            return (Criteria) this;
        }

        public Criteria andKeyManufactureIsNull() {
            addCriterion("KeyManufacture is null");
            return (Criteria) this;
        }

        public Criteria andKeyManufactureIsNotNull() {
            addCriterion("KeyManufacture is not null");
            return (Criteria) this;
        }

        public Criteria andKeyManufactureEqualTo(String value) {
            addCriterion("KeyManufacture =", value, "keyManufacture");
            return (Criteria) this;
        }

        public Criteria andKeyManufactureNotEqualTo(String value) {
            addCriterion("KeyManufacture <>", value, "keyManufacture");
            return (Criteria) this;
        }

        public Criteria andKeyManufactureGreaterThan(String value) {
            addCriterion("KeyManufacture >", value, "keyManufacture");
            return (Criteria) this;
        }

        public Criteria andKeyManufactureGreaterThanOrEqualTo(String value) {
            addCriterion("KeyManufacture >=", value, "keyManufacture");
            return (Criteria) this;
        }

        public Criteria andKeyManufactureLessThan(String value) {
            addCriterion("KeyManufacture <", value, "keyManufacture");
            return (Criteria) this;
        }

        public Criteria andKeyManufactureLessThanOrEqualTo(String value) {
            addCriterion("KeyManufacture <=", value, "keyManufacture");
            return (Criteria) this;
        }

        public Criteria andKeyManufactureLike(String value) {
            addCriterion("KeyManufacture like", value, "keyManufacture");
            return (Criteria) this;
        }

        public Criteria andKeyManufactureNotLike(String value) {
            addCriterion("KeyManufacture not like", value, "keyManufacture");
            return (Criteria) this;
        }

        public Criteria andKeyManufactureIn(List<String> values) {
            addCriterion("KeyManufacture in", values, "keyManufacture");
            return (Criteria) this;
        }

        public Criteria andKeyManufactureNotIn(List<String> values) {
            addCriterion("KeyManufacture not in", values, "keyManufacture");
            return (Criteria) this;
        }

        public Criteria andKeyManufactureBetween(String value1, String value2) {
            addCriterion("KeyManufacture between", value1, value2, "keyManufacture");
            return (Criteria) this;
        }

        public Criteria andKeyManufactureNotBetween(String value1, String value2) {
            addCriterion("KeyManufacture not between", value1, value2, "keyManufacture");
            return (Criteria) this;
        }

        public Criteria andSVSServerTypeIsNull() {
            addCriterion("SVSServerType is null");
            return (Criteria) this;
        }

        public Criteria andSVSServerTypeIsNotNull() {
            addCriterion("SVSServerType is not null");
            return (Criteria) this;
        }

        public Criteria andSVSServerTypeEqualTo(String value) {
            addCriterion("SVSServerType =", value, "SVSServerType");
            return (Criteria) this;
        }

        public Criteria andSVSServerTypeNotEqualTo(String value) {
            addCriterion("SVSServerType <>", value, "SVSServerType");
            return (Criteria) this;
        }

        public Criteria andSVSServerTypeGreaterThan(String value) {
            addCriterion("SVSServerType >", value, "SVSServerType");
            return (Criteria) this;
        }

        public Criteria andSVSServerTypeGreaterThanOrEqualTo(String value) {
            addCriterion("SVSServerType >=", value, "SVSServerType");
            return (Criteria) this;
        }

        public Criteria andSVSServerTypeLessThan(String value) {
            addCriterion("SVSServerType <", value, "SVSServerType");
            return (Criteria) this;
        }

        public Criteria andSVSServerTypeLessThanOrEqualTo(String value) {
            addCriterion("SVSServerType <=", value, "SVSServerType");
            return (Criteria) this;
        }

        public Criteria andSVSServerTypeLike(String value) {
            addCriterion("SVSServerType like", value, "SVSServerType");
            return (Criteria) this;
        }

        public Criteria andSVSServerTypeNotLike(String value) {
            addCriterion("SVSServerType not like", value, "SVSServerType");
            return (Criteria) this;
        }

        public Criteria andSVSServerTypeIn(List<String> values) {
            addCriterion("SVSServerType in", values, "SVSServerType");
            return (Criteria) this;
        }

        public Criteria andSVSServerTypeNotIn(List<String> values) {
            addCriterion("SVSServerType not in", values, "SVSServerType");
            return (Criteria) this;
        }

        public Criteria andSVSServerTypeBetween(String value1, String value2) {
            addCriterion("SVSServerType between", value1, value2, "SVSServerType");
            return (Criteria) this;
        }

        public Criteria andSVSServerTypeNotBetween(String value1, String value2) {
            addCriterion("SVSServerType not between", value1, value2, "SVSServerType");
            return (Criteria) this;
        }

        public Criteria andTSSServerTypeIsNull() {
            addCriterion("TSSServerType is null");
            return (Criteria) this;
        }

        public Criteria andTSSServerTypeIsNotNull() {
            addCriterion("TSSServerType is not null");
            return (Criteria) this;
        }

        public Criteria andTSSServerTypeEqualTo(String value) {
            addCriterion("TSSServerType =", value, "TSSServerType");
            return (Criteria) this;
        }

        public Criteria andTSSServerTypeNotEqualTo(String value) {
            addCriterion("TSSServerType <>", value, "TSSServerType");
            return (Criteria) this;
        }

        public Criteria andTSSServerTypeGreaterThan(String value) {
            addCriterion("TSSServerType >", value, "TSSServerType");
            return (Criteria) this;
        }

        public Criteria andTSSServerTypeGreaterThanOrEqualTo(String value) {
            addCriterion("TSSServerType >=", value, "TSSServerType");
            return (Criteria) this;
        }

        public Criteria andTSSServerTypeLessThan(String value) {
            addCriterion("TSSServerType <", value, "TSSServerType");
            return (Criteria) this;
        }

        public Criteria andTSSServerTypeLessThanOrEqualTo(String value) {
            addCriterion("TSSServerType <=", value, "TSSServerType");
            return (Criteria) this;
        }

        public Criteria andTSSServerTypeLike(String value) {
            addCriterion("TSSServerType like", value, "TSSServerType");
            return (Criteria) this;
        }

        public Criteria andTSSServerTypeNotLike(String value) {
            addCriterion("TSSServerType not like", value, "TSSServerType");
            return (Criteria) this;
        }

        public Criteria andTSSServerTypeIn(List<String> values) {
            addCriterion("TSSServerType in", values, "TSSServerType");
            return (Criteria) this;
        }

        public Criteria andTSSServerTypeNotIn(List<String> values) {
            addCriterion("TSSServerType not in", values, "TSSServerType");
            return (Criteria) this;
        }

        public Criteria andTSSServerTypeBetween(String value1, String value2) {
            addCriterion("TSSServerType between", value1, value2, "TSSServerType");
            return (Criteria) this;
        }

        public Criteria andTSSServerTypeNotBetween(String value1, String value2) {
            addCriterion("TSSServerType not between", value1, value2, "TSSServerType");
            return (Criteria) this;
        }

        public Criteria andSealTypeIsNull() {
            addCriterion("SealType is null");
            return (Criteria) this;
        }

        public Criteria andSealTypeIsNotNull() {
            addCriterion("SealType is not null");
            return (Criteria) this;
        }

        public Criteria andSealTypeEqualTo(String value) {
            addCriterion("SealType =", value, "sealType");
            return (Criteria) this;
        }

        public Criteria andSealTypeNotEqualTo(String value) {
            addCriterion("SealType <>", value, "sealType");
            return (Criteria) this;
        }

        public Criteria andSealTypeGreaterThan(String value) {
            addCriterion("SealType >", value, "sealType");
            return (Criteria) this;
        }

        public Criteria andSealTypeGreaterThanOrEqualTo(String value) {
            addCriterion("SealType >=", value, "sealType");
            return (Criteria) this;
        }

        public Criteria andSealTypeLessThan(String value) {
            addCriterion("SealType <", value, "sealType");
            return (Criteria) this;
        }

        public Criteria andSealTypeLessThanOrEqualTo(String value) {
            addCriterion("SealType <=", value, "sealType");
            return (Criteria) this;
        }

        public Criteria andSealTypeLike(String value) {
            addCriterion("SealType like", value, "sealType");
            return (Criteria) this;
        }

        public Criteria andSealTypeNotLike(String value) {
            addCriterion("SealType not like", value, "sealType");
            return (Criteria) this;
        }

        public Criteria andSealTypeIn(List<String> values) {
            addCriterion("SealType in", values, "sealType");
            return (Criteria) this;
        }

        public Criteria andSealTypeNotIn(List<String> values) {
            addCriterion("SealType not in", values, "sealType");
            return (Criteria) this;
        }

        public Criteria andSealTypeBetween(String value1, String value2) {
            addCriterion("SealType between", value1, value2, "sealType");
            return (Criteria) this;
        }

        public Criteria andSealTypeNotBetween(String value1, String value2) {
            addCriterion("SealType not between", value1, value2, "sealType");
            return (Criteria) this;
        }

        public Criteria andProjectInitDateIsNull() {
            addCriterion("ProjectInitDate is null");
            return (Criteria) this;
        }

        public Criteria andProjectInitDateIsNotNull() {
            addCriterion("ProjectInitDate is not null");
            return (Criteria) this;
        }

        public Criteria andProjectInitDateEqualTo(Date value) {
            addCriterion("ProjectInitDate =", value, "projectInitDate");
            return (Criteria) this;
        }

        public Criteria andProjectInitDateNotEqualTo(Date value) {
            addCriterion("ProjectInitDate <>", value, "projectInitDate");
            return (Criteria) this;
        }

        public Criteria andProjectInitDateGreaterThan(Date value) {
            addCriterion("ProjectInitDate >", value, "projectInitDate");
            return (Criteria) this;
        }

        public Criteria andProjectInitDateGreaterThanOrEqualTo(Date value) {
            addCriterion("ProjectInitDate >=", value, "projectInitDate");
            return (Criteria) this;
        }

        public Criteria andProjectInitDateLessThan(Date value) {
            addCriterion("ProjectInitDate <", value, "projectInitDate");
            return (Criteria) this;
        }

        public Criteria andProjectInitDateLessThanOrEqualTo(Date value) {
            addCriterion("ProjectInitDate <=", value, "projectInitDate");
            return (Criteria) this;
        }

        public Criteria andProjectInitDateIn(List<Date> values) {
            addCriterion("ProjectInitDate in", values, "projectInitDate");
            return (Criteria) this;
        }

        public Criteria andProjectInitDateNotIn(List<Date> values) {
            addCriterion("ProjectInitDate not in", values, "projectInitDate");
            return (Criteria) this;
        }

        public Criteria andProjectInitDateBetween(Date value1, Date value2) {
            addCriterion("ProjectInitDate between", value1, value2, "projectInitDate");
            return (Criteria) this;
        }

        public Criteria andProjectInitDateNotBetween(Date value1, Date value2) {
            addCriterion("ProjectInitDate not between", value1, value2, "projectInitDate");
            return (Criteria) this;
        }

        public Criteria andProjectStatusIsNull() {
            addCriterion("ProjectStatus is null");
            return (Criteria) this;
        }

        public Criteria andProjectStatusIsNotNull() {
            addCriterion("ProjectStatus is not null");
            return (Criteria) this;
        }

        public Criteria andProjectStatusEqualTo(String value) {
            addCriterion("ProjectStatus =", value, "projectStatus");
            return (Criteria) this;
        }

        public Criteria andProjectStatusNotEqualTo(String value) {
            addCriterion("ProjectStatus <>", value, "projectStatus");
            return (Criteria) this;
        }

        public Criteria andProjectStatusGreaterThan(String value) {
            addCriterion("ProjectStatus >", value, "projectStatus");
            return (Criteria) this;
        }

        public Criteria andProjectStatusGreaterThanOrEqualTo(String value) {
            addCriterion("ProjectStatus >=", value, "projectStatus");
            return (Criteria) this;
        }

        public Criteria andProjectStatusLessThan(String value) {
            addCriterion("ProjectStatus <", value, "projectStatus");
            return (Criteria) this;
        }

        public Criteria andProjectStatusLessThanOrEqualTo(String value) {
            addCriterion("ProjectStatus <=", value, "projectStatus");
            return (Criteria) this;
        }

        public Criteria andProjectStatusLike(String value) {
            addCriterion("ProjectStatus like", value, "projectStatus");
            return (Criteria) this;
        }

        public Criteria andProjectStatusNotLike(String value) {
            addCriterion("ProjectStatus not like", value, "projectStatus");
            return (Criteria) this;
        }

        public Criteria andProjectStatusIn(List<String> values) {
            addCriterion("ProjectStatus in", values, "projectStatus");
            return (Criteria) this;
        }

        public Criteria andProjectStatusNotIn(List<String> values) {
            addCriterion("ProjectStatus not in", values, "projectStatus");
            return (Criteria) this;
        }

        public Criteria andProjectStatusBetween(String value1, String value2) {
            addCriterion("ProjectStatus between", value1, value2, "projectStatus");
            return (Criteria) this;
        }

        public Criteria andProjectStatusNotBetween(String value1, String value2) {
            addCriterion("ProjectStatus not between", value1, value2, "projectStatus");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table projectinfo
     *
     * @mbggenerated do_not_delete_during_merge Tue Nov 04 22:12:17 CST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table projectinfo
     *
     * @mbggenerated Tue Nov 04 22:12:17 CST 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}