package cn.org.hbca.project.dao;

import cn.org.hbca.project.model.Projectinfo;
import cn.org.hbca.project.model.ProjectinfoExample;
import cn.org.hbca.project.model.ProjectinfoWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProjectinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projectinfo
     *
     * @mbggenerated Thu Nov 13 23:06:13 CST 2014
     */
    int countByExample(ProjectinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projectinfo
     *
     * @mbggenerated Thu Nov 13 23:06:13 CST 2014
     */
    int deleteByExample(ProjectinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projectinfo
     *
     * @mbggenerated Thu Nov 13 23:06:13 CST 2014
     */
    int deleteByPrimaryKey(String projectId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projectinfo
     *
     * @mbggenerated Thu Nov 13 23:06:13 CST 2014
     */
    int insert(ProjectinfoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projectinfo
     *
     * @mbggenerated Thu Nov 13 23:06:13 CST 2014
     */
    int insertSelective(ProjectinfoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projectinfo
     *
     * @mbggenerated Thu Nov 13 23:06:13 CST 2014
     */
    List<ProjectinfoWithBLOBs> selectByExampleWithBLOBs(ProjectinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projectinfo
     *
     * @mbggenerated Thu Nov 13 23:06:13 CST 2014
     */
    List<Projectinfo> selectByExample(ProjectinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projectinfo
     *
     * @mbggenerated Thu Nov 13 23:06:13 CST 2014
     */
    ProjectinfoWithBLOBs selectByPrimaryKey(String projectId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projectinfo
     *
     * @mbggenerated Thu Nov 13 23:06:13 CST 2014
     */
    int updateByExampleSelective(@Param("record") ProjectinfoWithBLOBs record, @Param("example") ProjectinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projectinfo
     *
     * @mbggenerated Thu Nov 13 23:06:13 CST 2014
     */
    int updateByExampleWithBLOBs(@Param("record") ProjectinfoWithBLOBs record, @Param("example") ProjectinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projectinfo
     *
     * @mbggenerated Thu Nov 13 23:06:13 CST 2014
     */
    int updateByExample(@Param("record") Projectinfo record, @Param("example") ProjectinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projectinfo
     *
     * @mbggenerated Thu Nov 13 23:06:13 CST 2014
     */
    int updateByPrimaryKeySelective(ProjectinfoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projectinfo
     *
     * @mbggenerated Thu Nov 13 23:06:13 CST 2014
     */
    int updateByPrimaryKeyWithBLOBs(ProjectinfoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projectinfo
     *
     * @mbggenerated Thu Nov 13 23:06:13 CST 2014
     */
    int updateByPrimaryKey(Projectinfo record);
}